export const DI = {
  PROFILES_BASE_DIR: Symbol('PROFILES_BASE_DIR'),
  PROFILE_PARSER: Symbol('PROFILE_PARSER'),
  DEVELOPER_PROFILE_REPOSITORY: Symbol('DEVELOPER_PROFILE_REPOSITORY'),
  IMPROVEMENT_COLLECTOR: Symbol('IMPROVEMENT_COLLECTOR'),
  SIZE_LEVEL_CALCULATOR: Symbol('SIZE_LEVEL_CALCULATOR'),
  INTERVENTION_LEVEL_CALCULATOR: Symbol('INTERVENTION_LEVEL_CALCULATOR'),
  PARALLELISM_LEVEL_CALCULATOR: Symbol('PARALLELISM_LEVEL_CALCULATOR'),
  DEVELOPER_PROFILE_EVALUATOR: Symbol('DEVELOPER_PROFILE_EVALUATOR'),
  EVALUATE_DEVELOPER_PROFILE_USE_CASE: Symbol('EVALUATE_DEVELOPER_PROFILE_USE_CASE'),
} as const;
